# Generated by Django 5.1.3 on 2024-12-01 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wrap", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Wrap",
        ),
    ]
