# Generated by Django 5.1.3 on 2024-12-01 17:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wrap", "0002_delete_wrap"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wrap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artist_ids", models.JSONField()),
                ("album_ids", models.JSONField()),
                ("is_duo", models.BooleanField()),
                ("time_range", models.CharField(max_length=15)),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "created_by",
                    models.ManyToManyField(
                        related_name="created_wraps", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "liked_by",
                    models.ManyToManyField(
                        related_name="liked_wraps", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
