# Generated by Django 5.1 on 2024-11-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="access_token",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="refresh_token",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="spotify_id",
            field=models.TextField(unique=True),
        ),
    ]
